spring.datasource.url=jdbc:postgresql://localhost:5432/home_services
spring.datasource.username=postgres
spring.datasource.password= postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sin.mhm@gmail.com
spring.mail.password=uycriwlrcmhlehja
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Set log level
logging.level.root=INFO

# Log file name and path
logging.file.name=logs/app.log

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.directory=logs
server.tomcat.accesslog.prefix=access
server.tomcat.accesslog.suffix=.log


# Optional: maximum file size & rotation settings
# For advanced use, use logback-spring.xml instead